# Generated by Django 5.1 on 2026-09-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knownservice',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='knownservice',
            index=models.Index(fields=['name'], name='known_servi_name_833d66_idx'),
        ),
    ]
